default_language_version:
  python: python3.8

repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.1.0
  hooks:
  - id: check-added-large-files
  - id: check-case-conflict
  - id: check-json
  - id: check-merge-conflict
  - id: check-symlinks
  - id: check-toml
  - id: end-of-file-fixer
  - id: trailing-whitespace
- repo: https://github.com/pre-commit/mirrors-prettier
  rev: v2.5.1
  hooks:
    - id: prettier
      files: \.(js|ts|jsx|tsx|css|less|json|markdown|md)$
- repo: https://github.com/pre-commit/mirrors-eslint
  rev: v8.8.0
  hooks:
  - id: eslint
    args:
    - --config=package.json
    - --fix
    additional_dependencies:
    - eslint@8.8.0
- repo: https://github.com/thibaudcolas/curlylint
  rev: v0.13.0
  hooks:
  - id: curlylint
    types: [html]
- repo: https://github.com/asottile/pyupgrade
  rev: v2.31.0
  hooks:
  - id: pyupgrade
    args: [--py310-plus]
- repo: https://github.com/hakancelik96/unimport
  rev: 0.9.5
  hooks:
  - id: unimport
    args:
      [--remove,  --include-star-import, --ignore-init, --gitignore]
- repo: https://github.com/psf/black
  rev: 22.1.0
  hooks:
  - id: black
    language_version: python3
- repo: https://github.com/pycqa/isort
  rev: 5.10.1
  hooks:
  - id: isort
- repo: https://github.com/PyCQA/flake8
  rev: 4.0.1
  hooks:
  - id: flake8
    additional_dependencies:
    - flake8-bugbear
    - flake8-comprehensions
    - flake8-no-pep420
    - flake8-tidy-imports
