version: "3.9"

services:
  db:
    image: postgres:14.0
    volumes:
      - ./_data/postgres/:/var/lib/postgresql/data
    env_file:
      - .env.prod
    ports:
      - 5432:5432
  web:
    container_name: sigipo
    build: .
    command:
      sh -c "python manage.py collectstatic --no-input --clear &&
        python manage.py migrate &&
        gunicorn --workers=4 --bind=0.0.0.0:8000 config.wsgi:application"
    volumes:
        - .:/code
        - static_volume:/code/staticfiles/
        - media_volume:/code/mediafiles/
    env_file:
      - .env.prod
    expose:
      - 8000
    depends_on:
      - db
    restart: always
  nginx:
    build: ./nginx
    container_name: nginx
    ports:
      - 80:80
    volumes:
      - static_volume:/code/staticfiles/
      - media_volume:/code/media/
    depends_on:
      - web
    restart: always
volumes:
  static_volume:
  media_volume:
