# Generated by Django 4.2.1 on 2024-02-04 08:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("employee", "0004_alter_doctor_options_alter_group_options"),
        ("patient", "0009_view_name_change"),
    ]

    operations = [
        migrations.CreateModel(
            name="Disease",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Nombre")),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Descripción"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Dosimetrist",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Nombre"
                    ),
                ),
            ],
            options={
                "verbose_name": "Dosimetrista",
                "verbose_name_plural": "Dosimetristas",
                "ordering": ["pk"],
            },
        ),
        migrations.CreateModel(
            name="Physicist",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Nombre"
                    ),
                ),
            ],
            options={
                "verbose_name": "Físico",
                "verbose_name_plural": "Físicos",
                "ordering": ["pk"],
            },
        ),
        migrations.CreateModel(
            name="Technic",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Nombre"
                    ),
                ),
            ],
            options={
                "verbose_name": "Técnico",
                "verbose_name_plural": "Técnicos",
                "ordering": ["pk"],
            },
        ),
        migrations.CreateModel(
            name="Treatment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Nombre")),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Descripción"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TACRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "id_code",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="ID"
                    ),
                ),
                (
                    "date_of_request",
                    models.DateField(
                        blank=True, null=True, verbose_name="Fecha de solicitud"
                    ),
                ),
                (
                    "bb_position",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Posición del BB",
                    ),
                ),
                (
                    "location",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Localización",
                    ),
                ),
                (
                    "upper_limit",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Límite Superior",
                    ),
                ),
                (
                    "lower_limit",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Límite Inferior",
                    ),
                ),
                (
                    "distance_betwen_cuts",
                    models.PositiveIntegerField(
                        blank=True,
                        null=True,
                        verbose_name="Distancia entre Cortes (mm)",
                    ),
                ),
                (
                    "dosimetrist",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="radiotherapy.dosimetrist",
                        verbose_name="Dosimetrista",
                    ),
                ),
                (
                    "medic_that_requests",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="employee.doctor",
                        verbose_name="Doctor",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="patient.patient",
                        verbose_name="Paciente",
                    ),
                ),
                (
                    "physicist",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="radiotherapy.physicist",
                        verbose_name="Físico",
                    ),
                ),
            ],
            options={
                "verbose_name": "Solicitud de TAC",
                "verbose_name_plural": "Solicitudes de TAC",
                "ordering": ["pk"],
            },
        ),
        migrations.CreateModel(
            name="GeneralDatasheet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "id_code",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="ID"
                    ),
                ),
                (
                    "serv_proc",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Serv. Proc.",
                    ),
                ),
                (
                    "amb",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Amb."
                    ),
                ),
                (
                    "hosp",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Hosp."
                    ),
                ),
                (
                    "no_locaclizacion",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="No. Localización",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, null=True, verbose_name="Localización y Descripción"
                    ),
                ),
                (
                    "anatopathologic_diagnose",
                    models.TextField(
                        blank=True,
                        null=True,
                        verbose_name="Diagnóstico Anatomopatológico",
                    ),
                ),
                (
                    "t",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="T"
                    ),
                ),
                (
                    "n",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="N"
                    ),
                ),
                (
                    "m",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="M"
                    ),
                ),
                (
                    "stage",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Etapa"
                    ),
                ),
                ("date", models.DateField(blank=True, null=True, verbose_name="Fecha")),
                (
                    "central_cons_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Fecha de consulta Central"
                    ),
                ),
                (
                    "new_cases_cons_date",
                    models.DateField(
                        blank=True,
                        null=True,
                        verbose_name="Fecha de consulta Casos Nuevos",
                    ),
                ),
                (
                    "first_stage_simulation_date",
                    models.DateField(
                        blank=True,
                        null=True,
                        verbose_name="Fecha de Simulación 1ra Fase",
                    ),
                ),
                (
                    "second_stage_simulation_date",
                    models.DateField(
                        blank=True,
                        null=True,
                        verbose_name="Fecha de Simulación 2da Fase",
                    ),
                ),
                (
                    "tac_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Fecha de TAC"
                    ),
                ),
                (
                    "paint_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Fecha de Pintado"
                    ),
                ),
                (
                    "planing_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Fecha de Planificado"
                    ),
                ),
                (
                    "first_stage_treatment_start_date",
                    models.DateField(
                        blank=True,
                        null=True,
                        verbose_name="Fecha inicio tratamiento 1ra Fase",
                    ),
                ),
                (
                    "second_stage_treatment_start_date",
                    models.DateField(
                        blank=True,
                        null=True,
                        verbose_name="Fecha inicio tratamiento 2da Fase",
                    ),
                ),
                (
                    "registered_by",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Registrado por",
                    ),
                ),
                (
                    "Technic",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="radiotherapy.technic",
                        verbose_name="Técnico",
                    ),
                ),
                (
                    "dosimetrist",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="radiotherapy.dosimetrist",
                        verbose_name="Dosimetrista",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="patient.patient",
                        verbose_name="Paciente",
                    ),
                ),
                (
                    "physicist",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="radiotherapy.physicist",
                        verbose_name="Físico",
                    ),
                ),
                (
                    "prev_treatments",
                    models.ManyToManyField(
                        to="radiotherapy.treatment", verbose_name="Tratamientos Previos"
                    ),
                ),
                (
                    "radiotherapist",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="employee.doctor",
                        verbose_name="Radioterapeuta",
                    ),
                ),
                (
                    "related_diseases",
                    models.ManyToManyField(
                        to="radiotherapy.disease", verbose_name="Enfermedades Asociadas"
                    ),
                ),
            ],
        ),
    ]
