# Generated by Django 4.1.6 on 2023-03-28 19:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("patient", "0005_alter_patient_options"),
        ("geographic_location", "0002_auto_20220612_0006"),
    ]

    operations = [
        migrations.CreateModel(
            name="DeathCertificate",
            fields=[
                (
                    "deathCertificate_number",
                    models.CharField(
                        default=None,
                        max_length=50,
                        primary_key=True,
                        serialize=False,
                        verbose_name="Número de Certificación de Defunción",
                    ),
                ),
                (
                    "direct_death_cause",
                    models.TextField(verbose_name="Causa de Muerte"),
                ),
                (
                    "indirect_death_cause",
                    models.JSONField(verbose_name="Causa que ocasiono"),
                ),
                (
                    "other_contibuting_diseases",
                    models.JSONField(verbose_name="Causa de Muerte"),
                ),
                (
                    "time_of_death",
                    models.DateTimeField(
                        auto_now_add=True, null=True, verbose_name="Fecha de defunción"
                    ),
                ),
                ("first_name", models.CharField(max_length=128, verbose_name="Nombre")),
                (
                    "last_name",
                    models.CharField(max_length=255, verbose_name="Apellidos"),
                ),
                (
                    "ocupation",
                    models.CharField(max_length=128, verbose_name="Ocupación"),
                ),
                (
                    "ScholarshipLevel",
                    models.IntegerField(
                        choices=[
                            (0, "Ninguno"),
                            (1, "Primaria"),
                            (2, "Secundaria Básica"),
                            (3, "Obrero Calificado"),
                            (4, "Pre-Universitario"),
                            (5, "Técnico Medio"),
                            (6, "Universitario"),
                            (7, "Ignorado(a)"),
                        ],
                        default=8,
                        verbose_name="Nivel de Escolaridad",
                    ),
                ),
                (
                    "CivilState",
                    models.IntegerField(
                        choices=[
                            (1, "Casado(a)"),
                            (2, "Unido"),
                            (3, "Divorciado"),
                            (4, "Seaprado"),
                            (5, "Viudo"),
                            (6, "Soltero"),
                            (7, "Ignorado(a)"),
                        ],
                        default=7,
                        verbose_name="Estado Cívil",
                    ),
                ),
                (
                    "ResidenceType",
                    models.IntegerField(
                        blank=True,
                        choices=[
                            (1, "Permanente"),
                            (2, "Temporal"),
                            (3, "Ignorado(a)"),
                        ],
                        null=True,
                        verbose_name="Tipo de Residencia",
                    ),
                ),
                (
                    "DeathPlace",
                    models.IntegerField(
                        choices=[
                            (1, "Cuerpo de Guardia Hospitalario"),
                            (2, "Ingreso Hospitalario"),
                            (3, "Policlínico"),
                            (4, "Otro Centro Hospitalario"),
                            (5, "Domicilio"),
                            (6, "Otro Lugar"),
                            (7, "Ignorado(a)"),
                        ],
                        default=7,
                        verbose_name="Sitio de Defunción",
                    ),
                ),
                (
                    "Pregnancy",
                    models.IntegerField(
                        choices=[(1, "Sí"), (2, "No"), (3, "Ignorado(a)")],
                        default=3,
                        verbose_name="Embarazo en los últimos 12 meses",
                    ),
                ),
                (
                    "PregnancyResult",
                    models.IntegerField(
                        blank=True,
                        choices=[
                            (1, "Aborto"),
                            (2, "Parto por Cesarea"),
                            (3, "Parto Pelviano"),
                            (4, "Murio estando embarazada"),
                            (5, "Ignorado(a)"),
                        ],
                        null=True,
                        verbose_name="Resultado del embarazo",
                    ),
                ),
                (
                    "date_of_pregnancy",
                    models.DateField(
                        blank=True, null=True, verbose_name="Fecha del embarazo"
                    ),
                ),
                (
                    "ConfirmationCauses",
                    models.IntegerField(
                        choices=[
                            (1, "Clinica"),
                            (2, "Investigación"),
                            (3, "Operación"),
                            (4, "Biopsia"),
                            (5, "Necropsia"),
                            (6, "Reconocimiento"),
                        ],
                        default=1,
                        verbose_name="Confirmación de las causas",
                    ),
                ),
                (
                    "CertficationMadeBy",
                    models.IntegerField(
                        choices=[
                            (1, "Guardia"),
                            (2, "Asistencia"),
                            (3, "Familia"),
                            (4, "Legista"),
                            (5, "Otro"),
                        ],
                        default=1,
                        verbose_name="Certificación realizada por médico de",
                    ),
                ),
                (
                    "LastSurgeries",
                    models.IntegerField(
                        choices=[(1, "Sí"), (2, "No"), (3, "Ignorado(a)")],
                        default=3,
                        verbose_name="Cirugías en las últimas 4 semanas",
                    ),
                ),
                (
                    "Surgery_reasons",
                    models.TextField(verbose_name="Causa de la Cirugía"),
                ),
                (
                    "ViolentDeathCauses",
                    models.IntegerField(
                        blank=True,
                        choices=[
                            (1, "Accidente"),
                            (2, "Suicidio"),
                            (3, "Homicidio"),
                            (4, "Otro"),
                            (5, "Por Investigar"),
                        ],
                        null=True,
                        verbose_name="Causa aparente de muerte violenta",
                    ),
                ),
                (
                    "date_of_injury",
                    models.DateField(
                        blank=True, null=True, verbose_name="Fecha de la lesión"
                    ),
                ),
                (
                    "place_where_injury_occurred",
                    models.TextField(verbose_name="Lugar donde ocurrio la lesión"),
                ),
                (
                    "event_description",
                    models.TextField(verbose_name="Descripcion de como ocurrio"),
                ),
                (
                    "Requesting_authority",
                    models.TextField(verbose_name="Autoridad que solicita"),
                ),
                ("Act_number", models.TextField(verbose_name="Número de Acta")),
                (
                    "born_municipality",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="born_municipality_death",
                        to="geographic_location.municipality",
                        verbose_name="Municipio natal",
                    ),
                ),
                (
                    "patient",
                    models.OneToOneField(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="patient.patient",
                    ),
                ),
                (
                    "residence_municipality",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="residence_municipality_death",
                        to="geographic_location.municipality",
                        verbose_name="Municipio de residencia",
                    ),
                ),
            ],
            options={
                "verbose_name": "Certificado de Defunción",
                "verbose_name_plural": "Certificados de Defunción",
                "ordering": ["pk"],
                "default_permissions": (),
            },
        ),
    ]
