# Generated by Django 4.1.6 on 2023-04-13 00:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("death_certificate", "0002_deathcertificate_indirect_death_cause_1_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="deathcertificate",
            name="indirect_death_cause_1",
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name="deathcertificate",
            name="indirect_death_cause_2",
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name="deathcertificate",
            name="indirect_death_cause_3",
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name="deathcertificate",
            name="other_contibuting_diseases",
            field=models.JSONField(default=dict),
        ),
    ]
