# Generated by Django 4.1.6 on 2023-03-29 18:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("death_certificate", "0002_alter_deathcertificate_scholarshiplevel"),
    ]

    operations = [
        migrations.AlterField(
            model_name="deathcertificate",
            name="indirect_death_cause",
            field=models.JSONField(verbose_name="Causa que ocasionó"),
        ),
        migrations.AlterField(
            model_name="deathcertificate",
            name="other_contibuting_diseases",
            field=models.JSONField(verbose_name="Otras enfermedades contribuyentes"),
        ),
    ]
