# Generated by Django 4.1.6 on 2023-04-13 01:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "death_certificate",
            "0004_rename_certfication_made_by_deathcertificate_certification_made_by",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="deathcertificate",
            old_name="other_contibuting_diseases",
            new_name="other_contributing_diseases",
        ),
        migrations.AlterField(
            model_name="deathcertificate",
            name="event_description",
            field=models.TextField(verbose_name="Descripción de como ocurrió"),
        ),
        migrations.AlterField(
            model_name="deathcertificate",
            name="place_where_injury_occurred",
            field=models.TextField(verbose_name="Lugar donde ocurrió la lesión"),
        ),
        migrations.AlterField(
            model_name="deathcertificate",
            name="surgery_reasons",
            field=models.TextField(verbose_name="Razón de la Cirugía"),
        ),
    ]
