# Generated by Django 4.1.7 on 2023-04-19 07:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "death_certificate",
            "0005_rename_other_contibuting_diseases_deathcertificate_other_contributing_diseases_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="deathcertificate",
            name="civil_state",
            field=models.IntegerField(
                choices=[
                    (1, "Casado(a)"),
                    (2, "Unido"),
                    (3, "Divorciado"),
                    (4, "Separado"),
                    (5, "Viudo"),
                    (6, "Soltero"),
                    (7, "Ignorado(a)"),
                ],
                default=7,
                verbose_name="Estado Cívil",
            ),
        ),
        migrations.AlterField(
            model_name="deathcertificate",
            name="event_description",
            field=models.TextField(
                blank=True, null=True, verbose_name="Descripción de como ocurrió"
            ),
        ),
        migrations.AlterField(
            model_name="deathcertificate",
            name="place_where_injury_occurred",
            field=models.TextField(
                blank=True, null=True, verbose_name="Lugar donde ocurrió la lesión"
            ),
        ),
        migrations.AlterField(
            model_name="deathcertificate",
            name="surgery_reasons",
            field=models.TextField(
                blank=True, null=True, verbose_name="Razón de la Cirugía"
            ),
        ),
    ]
