name: Code Coverage

on:
  push:
    branches: [ main, master ]

env:
  DJANGO_SETTINGS_MODULE: config.settings.develop

jobs:
  build:

    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: github_actions
        ports:
          - 5432:5432
        # needed because the postgres container does not provide a healthcheck
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
    - uses: actions/checkout@v1
      with:
        ref: ${{ github.head_ref }}
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements/develop.txt
    - name: Run Tests
      run: |
        pytest
    - name: Update Coverage
      run: |
        pip install coverage-badge
        coverage-badge -o coverage.svg -f
    - name: Commit badge
      run: |
        if git diff --exit-code; then
          echo "ANYTHING_TO_COMMIT=false" >> $GITHUB_ENV
        else
          echo "ANYTHING_TO_COMMIT=true" >> $GITHUB_ENV
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add coverage.svg
          git commit -m "Update coverage badge"
        fi
    - name: Push changes
      if: ${{ env.ANYTHING_TO_COMMIT }}
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: ${{ github.HEAD_REF   }}
