name: Django CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master, develop ]


env:
  DJANGO_SETTINGS_MODULE: config.settings.develop
  SECRET_KEY: SECRET_KEY

jobs:
  test:

    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: github_actions
        ports:
          - 5432:5432
        # needed because the postgres container does not provide a healthcheck
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements/develop.txt
    - name: Run Django System Checks
      run: python manage.py check
    - name: Run Tests
      run: |
        pytest
    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v3

    - name: Python Interrogate Check
      uses: JackMcKew/python-interrogate-check@main
      with:
        fail-under: 50
        badge-location: 'interrogate.svg'

    - name: Commit files
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add interrogate.svg
        git diff --exit-code || git commit -m "Update interrogate.svg" -a

    - name: Push changes
      if: success()
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.ACCESS_TOKEN }}
